apiVersion: apps/v1
kind: Deployment
metadata:
  name: decision-tree-deployment
  labels:
    app: decision-tree
spec:
  replicas: 1
  selector:
    matchLabels:
      app: decision-tree
  template:
    metadata:
      labels:
        app: decision-tree
    spec:
      containers:
      - name: decision-tree
        image: <your-acr-name>.azurecr.io/decision-tree:latest
        ports:
        - containerPort: 5000
